name: Testing Github Environments

on:
  push:
    branches:
      - feature/s3-bucket
      - main
                                               
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to environment
      run: |
        echo "Deploying to ${{ vars.ENV }} environment..."
        echo "API_TOKEN is ${{ secrets.API_TOKEN }}"